export const GODDESSES = [
  {
    day: 1,
    id: "shailaputri",
    name: "Śhailaputrī",
    title: "Daughter of the Mountain",
    color: "#f4efe6",
    accent: "#c9a227",
    vahana: "Nandi",
    image: "/assets/goddess-01-shailaputri.png",
    note: "Place at the lowest left niche. White silk, trident and lotus. Opens Navratri with grounding energy at the base of the makhar.",
  },
  {
    day: 2,
    id: "brahmacharini",
    name: "Brahmachāriṇī",
    title: "The Ascetic Seeker",
    color: "#efe8dc",
    accent: "#8b6914",
    vahana: "Walks on foot",
    image: "/assets/goddess-02-brahmacharini.png",
    note: "Second left niche. Japa mālā and kamaṇḍalu. A quieter, more austere panel beside the colourful gopuram.",
  },
  {
    day: 3,
    id: "chandraghanta",
    name: "Chandraghaṇṭā",
    title: "Moon-Bell Warrior",
    color: "#f3c98b",
    accent: "#c45c26",
    vahana: "Tiger",
    image: "/assets/goddess-03-chandraghanta.png",
    note: "Third left niche. Gold and saffron, crescent on the brow. Pairs with the tiger-yali carvings of the Meenakshi gopuram.",
  },
  {
    day: 4,
    id: "kushmanda",
    name: "Kūṣmāṇḍā",
    title: "The Cosmic Egg of Light",
    color: "#f0c14b",
    accent: "#d97706",
    vahana: "Lion",
    image: "/assets/goddess-04-kushmanda.png",
    note: "Upper left niche, closest to the crown. Radiant yellow — the ‘sun’ of the left tower.",
  },
  {
    day: 5,
    id: "skandamata",
    name: "Skandamātā",
    title: "Mother of Skanda",
    color: "#f7f1e1",
    accent: "#b45309",
    vahana: "Lion",
    image: "/assets/goddess-05-skandamata.png",
    note: "Crown niche above the 4×4 ft shrine. Maternal centre of the nine nights, blessing the family temple below.",
  },
  {
    day: 6,
    id: "katyayani",
    name: "Kātyāyanī",
    title: "The Warrior Maiden",
    color: "#c81e1e",
    accent: "#7f1d1d",
    vahana: "Lion",
    image: "/assets/goddess-06-katyayani.png",
    note: "Upper right niche. Deep Madurai red, echoing Meenakshi’s own martial grace.",
  },
  {
    day: 7,
    id: "kalaratri",
    name: "Kālarātri",
    title: "Night that Ends Fear",
    color: "#1c1218",
    accent: "#9f1239",
    vahana: "Donkey",
    image: "/assets/goddess-07-kalaratri.png",
    note: "Mid-right niche. Darkest panel of the wall — a deliberate contrast against turquoise gopuram plaster.",
  },
  {
    day: 8,
    id: "mahagauri",
    name: "Mahāgaurī",
    title: "The Great Fair One",
    color: "#f8f4ec",
    accent: "#d4af37",
    vahana: "Bull",
    image: "/assets/goddess-08-mahagauri.png",
    note: "Lower-mid right niche. Pearl white, like the silver halls of Madurai.",
  },
  {
    day: 9,
    id: "siddhidatri",
    name: "Siddhidātrī",
    title: "Giver of Attainments",
    color: "#d9468f",
    accent: "#be185d",
    vahana: "Lotus",
    image: "/assets/goddess-09-siddhidatri.png",
    note: "Lowest right niche. Completes Navratri at the base, opposite Shailaputri, seated on the golden lotus.",
  },
];
