export const GODDESSES = [
  {
    day: 1,
    id: "shailaputri",
    name: "Śhailaputrī",
    title: "Daughter of the Mountain",
    vahana: "Nandi",
    image: "/assets/goddess-01-shailaputri.png",
    x: -4.15,
    y: 2.05,
    note: "Lowest left frame on the 12×11 ft flex. White saree, bull, trident.",
  },
  {
    day: 2,
    id: "brahmacharini",
    name: "Brahmachāriṇī",
    title: "The Ascetic Seeker",
    vahana: "Walks on foot",
    image: "/assets/goddess-02-brahmacharini.png",
    x: -4.15,
    y: 4.55,
    note: "Left column, mid. Japa mālā and kamaṇḍalu — no mount.",
  },
  {
    day: 3,
    id: "chandraghanta",
    name: "Chandraghaṇṭā",
    title: "Moon-Bell Warrior",
    vahana: "Tiger",
    image: "/assets/goddess-03-chandraghanta.png",
    x: -4.15,
    y: 7.05,
    note: "Upper left. Ten arms, tiger, crescent on the brow.",
  },
  {
    day: 4,
    id: "kushmanda",
    name: "Kūṣmāṇḍā",
    title: "The Cosmic Egg of Light",
    vahana: "Lion",
    image: "/assets/goddess-04-kushmanda.png",
    x: -4.15,
    y: 9.5,
    note: "Top left. Golden yellow, eight arms, sun-like halo.",
  },
  {
    day: 5,
    id: "skandamata",
    name: "Skandamātā",
    title: "Mother of Skanda",
    vahana: "Lion",
    image: "/assets/goddess-05-skandamata.png",
    x: 0,
    y: 8.9,
    note: "Only frame above the temple, still on the banner — never inside the 4×4 marble shrine.",
  },
  {
    day: 6,
    id: "katyayani",
    name: "Kātyāyanī",
    title: "The Warrior Maiden",
    vahana: "Lion",
    image: "/assets/goddess-06-katyayani.png",
    x: 4.15,
    y: 9.5,
    note: "Top right. Red silk, sword, lion.",
  },
  {
    day: 7,
    id: "kalaratri",
    name: "Kālarātri",
    title: "Night that Ends Fear",
    vahana: "Donkey",
    image: "/assets/goddess-07-kalaratri.png",
    x: 4.15,
    y: 7.05,
    note: "Upper right. Dark complexion, wild hair — the one dark panel.",
  },
  {
    day: 8,
    id: "mahagauri",
    name: "Mahāgaurī",
    title: "The Great Fair One",
    vahana: "Bull",
    image: "/assets/goddess-08-mahagauri.png",
    x: 4.15,
    y: 4.55,
    note: "Right column, mid. White saree, bull.",
  },
  {
    day: 9,
    id: "siddhidatri",
    name: "Siddhidātrī",
    title: "Giver of Attainments",
    vahana: "Lotus",
    image: "/assets/goddess-09-siddhidatri.png",
    x: 4.15,
    y: 2.05,
    note: "Lowest right, opposite day 1. Pink-gold, seated on lotus.",
  },
];
